### ISSUE TITLE
Can't delete employee because of the foreign constraint on the bonuses and schedule tables

### ISSUE THREAD

**Issue by alisondraV** [ANDREYDEN/acacio#96]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/56138100/160501628-2c3bc031-1e77-485d-8dc5-c9f2f16480d3.png">

**Comment by ANDREYDEN** [comment]
Fixed by modifying constraints on `bonuses` and `shifts` tables to use cascade deletes. No code changes were required. I added 2 queries both in the dev and prod projects in Supabase SQL Editor.
